# Generated by Django 4.2.5 on 2023-09-09 21:30

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Indian phone number.', regex='^\\+?1?\\d{10}$')])),
                ('date_of_birth', models.DateField(validators=[dashboard.models.validate_age_range])),
                ('policy_cover', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50000000)])),
                ('policy_status', models.CharField(choices=[('Requirements Awaited', 'Requirements Awaited'), ('Requirements Closed', 'Requirements Closed'), ('Underwriting', 'Underwriting'), ('Policy Issued', 'Policy Issued'), ('Policy Rejected', 'Policy Rejected')], max_length=20)),
                ('policy_number', models.CharField(blank=True, max_length=50)),
                ('medical_type', models.CharField(blank=True, choices=[('Tele Medicals', 'Tele Medicals'), ('Physical Medicals', 'Physical Medicals')], max_length=20)),
                ('medicals_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Waiting for Report', 'Waiting for Report'), ('Done', 'Done')], max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
