# Generated by Django 4.2.5 on 2023-09-09 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_policy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
